scripts/chroot-fixups/rpm-python-extras.sh: remove buggy check
Fix the following error while trying to scan python-dns-2.0.0-1.el9:

    Processing files: python3-dns+dnssec-2.0.0-1.el9.noarch

    Error: The package name contains an extras name `dnssec` that was not found in the metadata.
    Check if the extras were removed from the project. If so, consider removing the subpackage and obsoleting it from another.

    error: Dependency tokens must begin with alpha-numeric, '_' or '/': *** PYTHON_EXTRAS_NOT_FOUND_ERROR___SEE_STDERR ***