unify mock invocation
without this patch, when running in a container, it fails with:

RuntimeError: mock will not run from the root account (needs an unprivileged uid so it can drop privs)