csmock: run rpm with '--without docs' instead of '--define docs\ 0'
Otherwise it is impossible to build java-service-wrapper-3.2.5-27.fc27:

>>> 2017-12-18 15:57:52 "script" "-aefqc" "\"/usr/bin/mock\" \"-r\" \"default\" \"--plugin-option=tmpfs:keep_mounted=True\" \"--disable-plugin=package_state\" \"--chroot\" \"/bin/su mockbuild -c \\\"rpmbuild -bs --nodeps /builddir/build/SPECS/java-service-wrapper.spec '--define' '_without_testsuite 1' '--define' 'apidocs 0' '--define' 'check\\\\\\\\
%%check\\\\\\\\
exit 0' '--define' 'libguestfs_runtests 0' '--define' 'runselftest 0' '--define' 'with_docs 0' '--define' 'with_publican 0' '--without' 'binfilter' '--without' 'langpacks' '--define' '_smp_mflags -j13' && sh -c 'cd /builddir/build/SRPMS && eval mv -v *.src.rpm java-service-wrapper-3.2.5-27.fc27.src.rpm || :'\\\"\"" "/dev/null"
INFO: mock.py version 1.2.18 starting (python version = 3.6.3)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
Start: run
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
Mock Version: 1.2.18
INFO: Mock Version: 1.2.18
Finish: chroot init
INFO: Running in chroot: ['/bin/su mockbuild -c "rpmbuild -bs --nodeps /builddir/build/SPECS/java-service-wrapper.spec \'--define\' \'_without_testsuite 1\' \'--define\' \'apidocs 0\' \'--define\' \'check\\\\\n%%check\\\\\nexit 0\' \'--define\' \'libguestfs_runtests 0\' \'--define\' \'runselftest 0\' \'--define\' \'with_docs 0\' \'--define\' \'with_publican 0\' \'--without\' \'binfilter\' \'--without\' \'langpacks\' \'--define\' \'_smp_mflags -j13\' && sh -c \'cd /builddir/build/SRPMS && eval mv -v *.src.rpm java-service-wrapper-3.2.5-27.fc27.src.rpm || :\'"']
Start: chroot ['/bin/su mockbuild -c "rpmbuild -bs --nodeps /builddir/build/SPECS/java-service-wrapper.spec \'--define\' \'_without_testsuite 1\' \'--define\' \'apidocs 0\' \'--define\' \'check\\\\\n%%check\\\\\nexit 0\' \'--define\' \'libguestfs_runtests 0\' \'--define\' \'runselftest 0\' \'--define\' \'with_docs 0\' \'--define\' \'with_publican 0\' \'--without\' \'binfilter\' \'--without\' \'langpacks\' \'--define\' \'_smp_mflags -j13\' && sh -c \'cd /builddir/build/SRPMS && eval mv -v *.src.rpm java-service-wrapper-3.2.5-27.fc27.src.rpm || :\'"']
error: Bad file: /builddir/build/SOURCES/cocoon-2.0.4-bin.tar.gz: No such file or directory
    Bad file: /builddir/build/SOURCES/cocoon-2.0.4-bin.tar.gz: No such file or directory