gcc: fix removal of _FORTIFY_SOURCE defines
Fixes the following warnings:
```
Error: COMPILER_WARNING:
rsync-3.2.7/main.c: warning: -D_FORTIFY_SOURCE defined but value is too low

Error: COMPILER_WARNING:
rsync-3.2.7/match.c: warning: -D_FORTIFY_SOURCE defined but value is too low
...
```

Fixes: f7ef6382d280df6ba57926ac3e3c537e8f85ae5e ("gcc: disable code fortification with sanitizers")