cppcheck: suppress error[unknownMacro] reports
... which are triggered when cppcheck is unable to parse the code.
Nothing really interesting for end users of csmock.  Examples follow:

Error: CPPCHECK_WARNING:
mariadb-10.5.13-downstream_modified/wsrep-lib/wsrep-API/v26/wsrep_api.h:595: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If In_C_you_should_use_my_bool_instead is a macro then please configure it.

Error: CPPCHECK_WARNING:
NetworkManager-1.35.7/src/libnm-client-impl/nm-checkpoint.c:128: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If NML_DBUS_META_PROPERTY_INIT_AO_PROP is a macro then please configure it.

Error: CPPCHECK_WARNING:
NetworkManager-1.35.7/src/libnm-client-impl/nm-client.c:7978: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If NML_DBUS_META_PROPERTY_INIT_AO_PROP is a macro then please configure it.

Error: CPPCHECK_WARNING:
NetworkManager-1.35.7/src/libnm-client-impl/nm-device-wifi-p2p.c:325: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If NML_DBUS_META_PROPERTY_INIT_AO_PROP is a macro then please configure it.

Error: CPPCHECK_WARNING:
NetworkManager-1.35.7/src/libnm-client-impl/nm-device-wifi.c:607: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If NML_DBUS_META_PROPERTY_INIT_AO_PROP is a macro then please configure it.

Error: CPPCHECK_WARNING:
NetworkManager-1.35.7/src/libnm-client-impl/nm-device.c:505: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If NML_DBUS_META_PROPERTY_INIT_O_PROP is a macro then please configure it.

Error: CPPCHECK_WARNING:
NetworkManager-1.35.7/src/libnm-client-impl/nm-ip-config.c:316: error[unknownMacro]: There is an unknown macro here somewhere. Configuration is required. If NML_DBUS_META_PROPERTY_INIT_FCN is a macro then please configure it.