csmock: copy /etc/resolv.conf into chroot when installing supermin
... to avoid build/scan failures like this:

+ ip route list
default via 10.37.135.254 dev eno1 proto dhcp metric 100
10.37.128.0/21 dev eno1 proto kernel scope link src 10.37.128.42 metric 100
10.88.0.0/16 dev cni0 proto kernel scope link src 10.88.0.1
+ ping -c 3 -w 20 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=50 time=4.36 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=50 time=4.38 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=50 time=4.36 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 4.356/4.365/4.379/0.010 ms
+ wget http://libguestfs.org -O /dev/null
--2019-10-09 15:25:25--  http://libguestfs.org/
Resolving libguestfs.org (libguestfs.org)... failed: Name or service not known.
wget: unable to resolve host address 'libguestfs.org'
+ mkdir cachedir repo
+ find /var/cache/dnf /var/cache/yum -type f -name '*.rpm' -print0
+ xargs -0 -n 1 cp -t repo
cp: missing file operand
Try 'cp --help' for more information.
error: Bad exit status from /var/tmp/rpm-tmp.lh2S1L (%build)