csmock --no-scan: fix traceback introduced by the recent refactoring
Traceback (most recent call last):
  File "/bin/csmock", line 1145, in <module>
    main()
  File "/bin/csmock", line 826, in main
    ec = do_scan(props, output, args, args.skip_patches)
  File "/bin/csmock", line 901, in do_scan
    mock.init_and_install(srpm_dup, props.install_pkgs, keep_going=props.keep_going)
UnboundLocalError: local variable 'srpm_dup' referenced before assignment