scripts/run-bandit.sh: do not assign array to string
Error: SHELLCHECK_WARNING:
/usr/share/csmock/scripts/run-bandit.sh:6:13: warning: Assigning an array
to a string! Assign as array, or use * instead of @ to concatenate. [SC2124]
4|   # $1 positional argument is security level definition
5|   SEC_LEVEL=$1
6|-> TARGET_PATH=${@:2:$#}
7|
8|   # Debug