csmock: do not explicitly create result dir for bld2repo
This was mistakenly added because of the following bug in bld2repo:

    https://github.com/rpm-software-management/modulemd-tools/pull/41

However, if bld2repo is not installed, it unnecessarily breaks the build:

>>> 2021-06-17 16:16:54	"bld2repo" "--build-id" "1604313" "--result-dir" "/tmp/csmockaoRZto/local-build-repo" "--koji-host" "https://brewhub.engineering.redhat.com/brewhub" "--koji-storage-host" "http://download.devel.redhat.com/brewroot"
[Errno 2] No such file or directory
>>> 2021-06-17 16:16:54	"/usr/bin/mock-unbuffered" "-r" "rhel-8-x86_64" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--quiet" "--installdeps" "/tmp/csmockaoRZto/babel-2.7.0-11.module+el8.5.0+11015+9c1c7c42.src.rpm"
[...]
>>> 2021-06-17 16:17:14	obtaining build info from brew: babel-2.7.0-11.module+el8.5.0+11015+9c1c7c42
>>> 2021-06-17 16:17:16	"/usr/bin/mock-unbuffered" "-r" "rhel-8-x86_64" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--quiet" "--installdeps" "/tmp/csmockaoRZto/babel-2.7.0-11.module+el8.5.0+11015+9c1c7c42.src.rpm" "--addrepo" "file:///tmp/csmockaoRZto/local-build-repo"
No matches found for the following disable plugin patterns: local, spacewalk
Errors during downloading metadata for repository '_tmp_csmockaoRZto_localbuildrepo':
  - Curl error (37): Couldn't read a file:// file for file:///tmp/csmockaoRZto/local-build-repo/repodata/repomd.xml [Couldn't open file /tmp/csmockaoRZto/local-build-repo/repodata/repomd.xml]
Error: Failed to download metadata for repo '_tmp_csmockaoRZto_localbuildrepo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried