gcc: drop the -no-canonical-prefixes flag by default
... because it does not work well with cswrap.  For example, the build
of woff2-1.0.2-3.el8 was failing with the following error:

/usr/lib64/cswrap/c++  -DFONT_COMPRESSION_BIN -D__STDC_FORMAT_MACROS -Dwoff2common_EXPORTS -I/builddir/build/BUILD/woff2-1.0.2/src -I/builddir/build/BUILD/woff2-1.0.2/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -fPIC   -no-canonical-prefixes -std=gnu++11 -o CMakeFiles/woff2common.dir/src/table_tags.cc.o -c /builddir/build/BUILD/woff2-1.0.2/src/table_tags.cc
c++: error trying to exec 'cc1plus': execvp: No such file or directory
make[2]: *** [CMakeFiles/woff2common.dir/build.make:66: CMakeFiles/woff2common.dir/src/table_tags.cc.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/woff2-1.0.2/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:221: CMakeFiles/woff2common.dir/all] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/woff2-1.0.2/x86_64-redhat-linux-gnu'
make: *** [Makefile:133: all] Error 2
make: Leaving directory '/builddir/build/BUILD/woff2-1.0.2/x86_64-redhat-linux-gnu'
error: Bad exit status from /var/tmp/rpm-tmp.Ilu3Xf (%build)